version: '3.7'
services:
  db:
    image: mongo:latest
    container_name: appfellas_db
    env_file:
      - ./.env
    ports:
      - 27017:${DB_PORT}
    volumes:
      - data:/Docker/data/db/
volumes:
  data:
