version: '3.7'
services:
  db:
    image: mongo:latest
    container_name: appfellas_db
    env_file:
      - ./.env
    ports:
      - 27017:${DB_PORT}
    volumes:
      - data:/Docker/data/db/
    networks:
      - appfellas

  server:
    build: ./server/
    container_name: appfellas_server
    env_file:
      - ./.env
    ports:
      - 3000:${SERVER_PORT}
    environment:
      - DB_HOST=db
    networks:
      - appfellas

  client:
    build: ./client/
    # restart: always # this line for server, because this code runs the container at startup
    container_name: appfellas_client
    ports:
      - 5173:5173
    networks:
      - appfellas

volumes:
  data:


networks:
  appfellas:
    driver: bridge
